- hosts: dev
  become: true
  tasks:
   - name: clone repo
     shell: git clone https://github.com/devops4all77/jenkinsakscicd.git && cd jenkinsakscicd
   - name: login to azure 
     shell: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID
   - name: set sub
     shell: az account set -s $AZURE_SUBSCRIPTION_ID
   - name: get creds of aks 
     shell: az aks get-credentials -g aks_rg -n aks_cls 
   - name: deploy to aks
     shell: kubectl apply -f helloapp.yaml
